runtime: nodejs20
service: default
service_account: github-actions-deployer@blog-angular-376623.iam.gserviceaccount.com

handlers:

- url: /
  static_files: frontend/dist/frontend/index.html
  upload: frontend/dist/frontend/index.html
- url: /(.*)
  static_files: frontend/dist/frontend/\1
  upload: frontend/dist/frontend/(.*)

# runtime: nodejs20
# service: default

# handlers:
#   - url: /.*
#     script: auto