runtime: nodejs18
service: default


handlers:

- url: /
  static_files: frontend/dist/frontend/index.html
  upload: frontend/dist/frontend/index.html
- url: /(.*)
  static_files: frontend/dist/frontend/\1
  upload: frontend/dist/frontend/(.*)