name: Deploy to Google App Engine

on:
  push:
    branches:
      - main  # Set this to the branch from which you want to deploy

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: ${{ secrets.GCP_PROJECT }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Install Dependencies
      run: |
        npm install

    - name: Build
      run: |
        npm run build  # or any other build command you use

    - name: Deploy to Google App Engine
      run: |
        gcloud app deploy --quiet

