name: Deploy to Google App Engine

on:
  push:
    branches:
      - main  # Set this to the branch from which you want to deploy
      - UAT
      - feat/add-cicd-workflow
runs:
  using: 'node20'

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
    - name: Authenticate GCP
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
    - name: Install Dependencies
      run: |
        npm install

    - name: Build
      run: |
        npm run build  # or any other build command you use

    - name: Deploy to Google App Engine
      run: |
        gcloud app deploy --quiet

