name: Deploy to Google App Engine

on:
  push:
    branches:
      - main  # Set this to the branch from which you want to deploy
      - UAT
      - feat/add-cicd-workflow


jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Authenticate GCP
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Install Dependencies
      run: |
        npm install
      working-directory: ./frontend

    - name: Build
      run: |
        npm run build  # or any other build command you use
      working-directory: ./frontend

    - name: Deploy to Google App Engine
      run: |
        gcloud app deploy --verbosity=debug

